version: "3"
services:
  mongo:
    image: mongo:latest
    restart: always
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "8080"
      DATABASE_HOSTNAME: "mongo"
      DATABASE_PORT: "27017"
      DATABASE_DATABASE: "db"
      MAILER_HOSTNAME: "smtp.gmail.com"
      MAILER_PORT: "465"
      MAILER_USER: ${MAILER_USER}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      OPEN_WEATHER_MAP_KEY: ${OPEN_WEATHER_MAP_KEY}
      YOUTUBE_KEY: ${YOUTUBE_KEY}
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      SERVER_PROTOCOL: "http"
      SERVER_HOSTNAME: "server"
      SERVER_PORT: "8080"
      SERVER_REDIRECT_HOSTNAME: "localhost"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
