version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: server/app/Dockerfile
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "4000"
  frontend:
    build:
      context: .
      dockerfile: web/app/Dockerfile
    environment:
      BACKEND_HOST: "backend:4000"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    ports:
      - "3000:3000"
