version: "3"
services:
  backend:
    build: backend/
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "8081"
    ports:
      - "8081:8081"
  frontend:
    build: frontend/
    environment:
      BACKEND_HOST: "localhost:8081"
      HOSTNAME: "0.0.0.0"
      PORT: "8080"
    ports:
      - "8080:8080"
