version: "3"
services:
  backend:
    build: backend/
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "4000"
  frontend:
    build: frontend/
    environment:
      BACKEND_HOST: "backend:4000"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    ports:
      - "3000:3000"
