name: Push

on:
  push:
    branches:
      - master
      - main

env:
  REPOSITORY_HOST: github.com
  REPOSITORY_OWNER: EpitechIT2020
  REPOSITORY_NAME: B-DEV-500-TLS-5-1-cardgames-guillaume.bonnet
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{ env.REPOSITORY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push
        run: |
          git push git@$REPOSITORY_HOST:/$REPOSITORY_OWNER/$REPOSITORY_NAME --force
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          docker build . -f server.Dockerfile -t epi-dashboard/server:latest
          docker build . -f web.Dockerfile -t epi-dashboard/web:latest
      - name: Tag images
        run: |
          docker tag epi-dashboard/server:latest registry.heroku.com/epi-dashboard-back/web
          docker tag epi-dashboard/web:latest registry.heroku.com/epi-dashboard/web
      - name: Login to heroku
        run: |
          heroku container:login
      - name: Push images
        run: |
          docker push registry.heroku.com/epi-dashboard-back/web
          docker push registry.heroku.com/epi-dashboard/web
      - name: Re-deploy apps
        run: |
          heroku container:release web -a epi-dashboard-back
          heroku container:release web -a epi-dashboard
