name: Push

on:
  push:
    branches:
      - master
      - main

env:
  REPOSITORY_HOST: github.com
  REPOSITORY_OWNER: EpitechIT2020
  REPOSITORY_NAME: B-DEV-500-TLS-5-1-cardgames-guillaume.bonnet
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{ env.REPOSITORY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push
        run: |
          git push git@$REPOSITORY_HOST:/$REPOSITORY_OWNER/$REPOSITORY_NAME --force
          
  web:
    name: "Web: Build and Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Build"
        run: |
          docker build . -f web.Dockerfile -t madfish5415/epitech-dashboard-web:latest madfish5415/epitech-dashboard-web:${GITHUB_SHA}
          
      - name: "Push"
        run: |
          docker push madfish5415/epitech-dashboard-web

          
  server:
    name: "Server: Build and Deploy"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: "Build"
        run: |
          docker build . -f server.Dockerfile -t madfish5415/epitech-dashboard-server:latest -t madfish5415/epitech-dashboard-server:${GITHUB_SHA}
          
      - name: "Push"
        run: |
          docker push madfish5415/epitech-dashboard-server
