name: Push

on:
  push:
    branches:
      - master
      - main

env:
  REPOSITORY_HOST: github.com
  REPOSITORY_OWNER: EpitechIT2020
  REPOSITORY_NAME: B-DEV-500-TLS-5-1-cardgames-guillaume.bonnet

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{ env.REPOSITORY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push
        run: |
          git push git@$REPOSITORY_HOST:/$REPOSITORY_OWNER/$REPOSITORY_NAME --force

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          docker-compose build

      - name: Tag images
        run: |
          docker tag dev_dashboard_2020_backend registry.heroku.com/epi-dashboard-back/web
          docker tag dev_dashboard_2020_frontend registry.heroku.com/epi-dashboard/web

      - name: Login to heroku
        run: |
          heroku container:login

      - name: Push images
        run: |
          docker push registry.heroku.com/epi-dashboard-back/web
          docker push registry.heroku.com/epi-dashboard/web

      - name: Re-deploy apps
        run: |
          heroku container:release web -a epi-dashboard-back
          heroku container:release web -a epi-dashboard
