name: Push

on:
  push:
    branches: [ master ]

env:
  DOCKER_IMAGE_OWNER: mrsquaare
  DOCKER_IMAGE_NAME: dashboard
  REPOSITORY_HOST: github.com
  REPOSITORY_OWNER: EpitechIT2020
  REPOSITORY_NAME: B-DEV-500-TLS-5-1-cardgames-guillaume.bonnet

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG="${TAG:-v1.0.0}"
          TAG="$(echo $TAG | grep -oP '(?<=^v).+')"
          MAJOR="$(echo $TAG | grep -oP '^\d+')"
          MINOR="$(echo $TAG | grep -oP '^\d+.\d+')"
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=major::$MAJOR"
          echo "::set-output name=minor::$MINOR"

      - name: Build
        run: |
          docker build . \
            -t $DOCKER_IMAGE_OWNER/$DOCKER_IMAGE_NAME:latest \
            -t $DOCKER_IMAGE_OWNER/$DOCKER_IMAGE_NAME:${{ steps.version.outputs.major }} \
            -t $DOCKER_IMAGE_OWNER/$DOCKER_IMAGE_NAME:${{ steps.version.outputs.minor }} \
            -t $DOCKER_IMAGE_OWNER/$DOCKER_IMAGE_NAME:${{ steps.version.outputs.tag }} \
            --build-arg IMAGE_CREATION=$(date --iso-8601=seconds) \
            --build-arg IMAGE_VERSION=${{ steps.version.outputs.tag }}

      - name: Push
          run: |
            docker push $DOCKER_IMAGE_OWNER/$DOCKER_IMAGE_NAME

  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{ env.REPOSITORY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push
        run: |
          git push git@$REPOSITORY_HOST:/$REPOSITORY_OWNER/$REPOSITORY_NAME --force
