name: Push

on:
  push:
    branches:
      - master
      - main

env:
  REPOSITORY_HOST: github.com
  REPOSITORY_OWNER: EpitechIT2020
  REPOSITORY_NAME: B-DEV-500-TLS-5-1-cardgames-guillaume.bonnet
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{ env.REPOSITORY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push
        run: |
          git push git@$REPOSITORY_HOST:/$REPOSITORY_OWNER/$REPOSITORY_NAME --force
          
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v1
        id: web-builder
        
      - uses: docker/setup-buildx-action@v1
        id: server-builder

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Web: Build and push"
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.web-builder.outputs.name }}
          context: ./
          file: ./web.Dockerfile
          push: true
          tags: madfish5415/epitech-dashboard-web:latest
          
      - name: "Server: Build and push"
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.server-builder.outputs.name }}
          context: ./
          file: ./server.Dockerfile
          push: true
          tags: madfish5415/epitech-dashboard-server:latest
